default:
  tags:
    - golang
stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $GITLAB_GROUP/$CI_PROJECT_NAME:latest


build:
  stage: build
  only:
    - main
  image: docker:25.0.1
  services:
    - name: docker:25.0.1-dind
      alias: docker
  variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
      DOCKER_DRIVER: overlay2
  before_script: 
    - echo $PAT | docker login $CI_REGISTRY -u $GITLAB_USER_LOGIN --password-stdin
  script:
    - docker build -t $CI_REGISTRY/$IMAGE_NAME .
    - docker push $CI_REGISTRY/$IMAGE_NAME

deploy:
  image: alpine:latest
  stage: deploy
  only:
    - main
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
 
  script:
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "echo hi"
  after_script:
    - rm -rf ~/.ssh
