version: '3.7'

services:
  # golang:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   container_name: taskema
  #   volumes:
  #     - ./uploads:/go/src/app/uploads
  #   restart: always
  #   depends_on:
  #     - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql_db
    volumes:
      - ./dbdata:/var/lib/taskema/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_ROOT_PASSWORD: taskemaappRoo7t0lk2o20
      MYSQL_DATABASE: taskemaapp_db
      MYSQL_USER: taskemaapp
      MYSQL_PASSWORD: taskemaappt0lk2o20


volumes:
  dbdata:
  uploads: