production:
  dialect: mysql
  datasource: taskemaapp:taskemaappt0lk2o20@(mysql:3306)/taskemaapp_db?parseTime=true
  dir: /go/src/app/datasource/mysql/migrations
  table: migrations

development:
  dialect: mysql
  datasource: taskemaapp:taskemaappt0lk2o20@(localhost:3306)/taskemaapp_db?parseTime=true
  dir: datasource/mysql/migrations
  table: migrations
